### ISSUE TITLE
question - Does MAPIE support multiple time series in tabular format?

### ISSUE THREAD

**Issue by Arsa-Nik** [AlgoTrading101/Conformal-Prediction-MAPIE-Algotrading101#1]
I wonder whether MapieTimeSeriesRegressor supports building prediction interval when input data is tabular form and contains multiple time series. Specifically how does it know to pull the right residuals in BlockBootstrap to build distribution when the scales of times series in input data are significantly different?

**Comment by IgorWounds** [comment]
Hi,
That is a very good question which is best to ask the people behind MAPIE on their main GitHub repository found here (https://github.com/scikit-learn-contrib/MAPIE). I personally can't answer it from the top of my head as I didn't try it on multiple time series in a tabular format.
